<?php

/**
 * Implements hook_theme().
 */
function searchstudio_theme($existing, $type, $theme, $path) {

  return [
    // Name of the theme hook. This is used in the controller to trigger the hook.
    'searchstudio' => [
      'render element' => 'children',
      'template' => 'searchstudio',
      'path' => $path . '/templates'
    ],
  ];

}

/**
 * Implements hook_page_attachments().
 */
function searchstudio_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'searchstudio/add-styling';
  $attachments['#attached']['library'][] = 'searchstudio/add-scripts';
}
